### ISSUE TITLE
Can you add support for weather data to the thermostats[] object?

### ISSUE THREAD

**Issue by PhracturedBlue** [nkgilley/python-ecobee-api#21]
Could you add 'includeWeather:true' to the thermostat request in get_thermostats()?
I would like to be able to track the difference between what the ecobee thinks the external temperature is vs my actual measurement.
The data I'm interested in appears to be in the following structure (once the above line is added to the request):
weather->forecasts->[0]->temperature

**Comment by nkgilley** [comment]
Please open up a PR and I'm happy to add it.

**Comment by PhracturedBlue** [comment]
Request pulled
