### ISSUE TITLE
typo in pyecobee/__init__.py

### ISSUE THREAD

**Issue by bartvast** [nkgilley/python-ecobee-api#27]
typo (line 203 of pyecobee/init.py does not provide the log_msg_action require argument to make_request)

Line 202,203 should probably be
if self.refresh_tokens():
return self.make_request(body,**log_msg_action**)

I originally filed this under home assistant 
https://github.com/home-assistant/home-assistant/issues/11918

**Comment by nkgilley** [comment]
This issue was fixed in release 0.0.15
