### ISSUE TITLE
Enhancement Request...include events

### ISSUE THREAD

**Issue by bthome** [nkgilley/python-ecobee-api#3]
Thank you for putting this library together.  I'm a Home Assistant user and been using the ecobee component to monitor several thermostats.  I am looking to monitor when someone overrides (HOLD) the schedule so I can be alerted.  I haven't been able to find a way to trap just that event.  I have been reading the ecobee API documentation and it requests the Event data.  I believe you would have to change your call to get_thermostats (line 122) to add includeEvents":"true".  The ecobee component would need to change to allow HA to be able to script \ notify based on an unexpected event.

Appreciate it.

**Comment by nkgilley** [comment]
fixed in 0.0.5
