### ISSUE TITLE
Refactoring needed to support Home Assistant config flow

### ISSUE THREAD

**Issue by marthoc** [nkgilley/python-ecobee-api#40]
Hi @nkgilley, I've been looking at adding a config flow for ecobee to Home Assistant. That means that some refactoring would be needed here since I need to wrap the sync calls used in this library with hass's async wrapper for use in the config flow, and I'm trying to avoid stray sync calls in this library (e.g. __init__ for the Ecobee class calls both request_pin() and update()). Would you be open to some PRs? In the future it could also be worth updating this to async for use in hass and I could spearhead that too if you're open to it.

**Comment by nkgilley** [comment]
Yes, I'm definitely open to that 🙂 Looking forward to your PRs
