### ISSUE TITLE
Ability to create vacations

### ISSUE THREAD

**Issue by FuzzyMistborn** [nkgilley/python-ecobee-api#42]
Can the ability to create vacations be added?

https://www.ecobee.com/home/developer/api/documentation/v1/functions/CreateVacation.shtml

**Comment by marthoc** [comment]
Just posting here to update @FuzzyMistborn that I've opened a new PR to add the create_vacation and delete_vacation services to Home Assistant. Follow the progress (and test, please) here: https://github.com/home-assistant/home-assistant/pull/26923.
