### ISSUE TITLE
Add support for SendMessage

### ISSUE THREAD

**Issue by pbros** [nkgilley/python-ecobee-api#5]
I'm a HomeAssistant user, and I was wondering if it would be possible to add support for the SendMessage API

https://www.ecobee.com/home/developer/api/documentation/v1/functions/SendMessage.shtml

This would allow HomeAssistant to send messages to the Ecobee thermostat's screen based on automation rules. 

OpenHAB seems to have implemented something similar
https://github.com/openhab/openhab/wiki/Ecobee-Binding

**Comment by nkgilley** [comment]
fixed in 0.0.5

**Comment by pbros** [comment]
Thanks :)

**Comment by nkgilley** [comment]
@pbros The dev branch of home-assistant now has this feature implemented as a notify component.  Just add this to your configuration.yaml:

```yaml
notify:
  platform: ecobee
  name: ecobee
```
