### ISSUE TITLE
Changes to Ecobee API

### ISSUE THREAD

**Issue by FuzzyMistborn** [nkgilley/python-ecobee-api#55]
Was looking something up and noticed this post that there will be changes to the API come November 1.

https://www.ecobee.com/home/developer/api/documentation/v1/auth/developer-migration-summary.shtml

**Comment by FuzzyMistborn** [comment]
Changes are now December 1st per an email I just received.

**Comment by pfletch101** [comment]
It looks as if the major changes (as far as pyecobee is concerned) have to do with a major increase in length (and more allowed characters) in the access and refresh tokens. As long as pyecobee is storing them as standard Python strings and not making any assumptions about their content, there should be no problem, other than some possible slowing of the handshaking process. I have asked for admission to the Early Access Program, and will report back.
